### ISSUE TITLE
Test data for development

### ISSUE THREAD

**Issue by r3dsm0k3** [IEEEKeralaSection/rescuekerala#481]
### Subject of the issue
To make the test data available for local dev, we could create a small dump (the bare minimum) and load it in the docker container for db (only after merging #445 though)

It can done easily by done by mounting a volume into the container and rest is taken care.

### Sample setup
```
#infra
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./dev-files/postgres:/docker-entrypoint-initdb.d
```

and in the `dev-files` folder

```
➜  rescuekerala git:(master) tree dev-files
dev-files
└── postgres
    └── dump.sql
```

Lets hear the thoughts on this one, triage it and if it is viable implement it. 

### Your environment
NA
